version: 0.1
default:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

sandbox:
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      image_repositories: []
      parameter_overrides: [
        "CallbackURLs=https://oauth.pstmn.io/v1/callback"
      ]
