version: 0.1
default:
  build:
    parameters:
      build_in_source: 'true'
      cached: 'true'
      parallel: 'true'
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      image_repositories: []