AWSTemplateFormatVersion: 2010-09-09
Description: besta-management-service
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 768

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml

  EchoESMFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: echo-esm/index.handler
      Events:
        EchoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /echo-esm
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - echo-esm/index.mjs
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  EchoJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: echo-js/index.handler
      Events:
        EchoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /echo-js
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - echo-js/index.js

Outputs:
  ApiURL:
    Description: API URL
    Value: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/api