AWSTemplateFormatVersion: 2010-09-09
Description: besta-management-service
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    MemorySize: 768

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml

  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: echo/index.handler
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - echo/index.mjs
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

Outputs:
  ApiURL:
    Description: API URL
    Value: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/api