name: Deploy API

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
    outputs:
      API_BASE_URL:
        value: ${{ jobs.deploy.outputs.API_BASE_URL }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      API_BASE_URL: ${{ steps.getStackOutputs.outputs.API_BASE_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.PIPELINE_EXECUTION_ROLE }}
          role-session-name: sam-deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          key: sam-deps
          path: |
            ~/.aws-sam

      - name: SAM Build and Deploy
        run: |
          npm install -g esbuild
          npm ci

          sam --info

          sam build

          sam deploy \
          --stack-name ${{inputs.STACK_NAME }} \
          --s3-bucket ${{ vars.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ vars.CLOUDFORMATION_EXECUTION_ROLE }}

      - id: getStackOutputs
        name: Get Stack Outputs
        run: |
          url=$(aws cloudformation describe-stacks --stack-name ${{inputs.STACK_NAME }} --query "Stacks[0].Outputs[?OutputKey=='ApiURL'].OutputValue" --output text)

          echo "# API" >> $GITHUB_STEP_SUMMARY
          echo "* API - $url" >> $GITHUB_STEP_SUMMARY

          echo "API_BASE_URL=$url" >> $GITHUB_OUTPUT