name: Deploy API

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
    outputs:
      API_BASE_URL:
        value: ${{ jobs.deploy.outputs.API_BASE_URL }}
      COGNITO_USER_POOL_ID:
        value: ${{ jobs.deploy.outputs.COGNITO_USER_POOL_ID }}
      COGNITO_USER_POOL_URL:
        value: ${{ jobs.deploy.outputs.COGNITO_USER_POOL_URL }}
      COGNITO_CLIENT_ID:
        value: ${{ jobs.deploy.outputs.COGNITO_CLIENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      API_BASE_URL: ${{ steps.getStackOutputs.outputs.API_BASE_URL }}
      COGNITO_USER_POOL_ID: ${{ steps.getStackOutputs.outputs.COGNITO_USER_POOL_ID }}
      COGNITO_USER_POOL_URL: ${{ steps.getStackOutputs.outputs.COGNITO_USER_POOL_URL }}
      COGNITO_CLIENT_ID: ${{ steps.getStackOutputs.outputs.COGNITO_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
          role-session-name: sam-deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: SAM Build and Deploy
        run: |
          npm install -g esbuild
          npm ci

          sam --info

          sam build

          sam deploy \
          --stack-name ${{inputs.STACK_NAME }} \
          --s3-bucket ${{ secrets.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}

      - id: getStackOutputs
        name: Get Stack Outputs
        run: |
          stackOutputJson=$(aws cloudformation describe-stacks --output json --stack-name ${{inputs.STACK_NAME }} --query "Stacks[0].Outputs")
          url=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="ApiURL") | .OutputValue')
          cognitoUserPoolId=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="CognitoUserPoolId") | .OutputValue')
          cognitoUserPoolUrl=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="CognitoUserPoolUrl") | .OutputValue')
          cognitoClientId=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="CognitoClientId") | .OutputValue')


          echo "# API" >> $GITHUB_STEP_SUMMARY
          echo "* API - $url" >> $GITHUB_STEP_SUMMARY
          echo "* Cognito User Pool Client ID - $cognitoUserPoolId" >> $GITHUB_STEP_SUMMARY
          echo "* Cognito User Pool Url - $cognitoUserPoolUrl" >> $GITHUB_STEP_SUMMARY
          echo "* Cognito Client Id - $cognitoClientId" >> $GITHUB_STEP_SUMMARY


          echo "API_BASE_URL=$url" >> $GITHUB_OUTPUT
          echo "COGNITO_USER_POOL_ID=$cognitoUserPoolId" >> $GITHUB_OUTPUT
          echo "COGNITO_USER_POOL_URL=$cognitoUserPoolUrl" >> $GITHUB_OUTPUT
          echo "COGNITO_CLIENT_ID=$cognitoClientId" >> $GITHUB_OUTPUT